apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: test123
  labels:
    app: test123
spec:
  replicas: 4
  selector:
    matchLabels:
      app: test123
  template:
    metadata:
      labels:
        app: test123
    spec:
      containers:
      - name: nginx
        image: registry.default.svc/wjoel/nginx
        ports:
        - containerPort: 80
