apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: test123
  namespace: default
  labels:
    app: test123
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test123
  template:
    metadata:
      labels:
        app: test123
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.8
        ports:
        - containerPort: 80
